server:
  port: 8080

spring:
  datasource:
    username: root
    password: Aa123456
    url: jdbc:mysql://localhost:3306/assignment

logging:
  level:
    com.example.assignment:

mybatis:
  mapper-locations: classpath:mapper/*.xml