server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: Ab123456
    url: jdbc:postgresql://localhost:5432/postgres

logging:
  level:
    com.example.assignment: INFO

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui-custom.html

initial:
  price: 100
