server:
  port: 8080

spring:
  datasource:
    username: root
    password: Chaojibai940!!
    url: jdbc:mysql://localhost:3306/assignment

logging:
  level:
    com.example.assignment:

mybatis:
  mapper-locations: classpath:mapper/*.xml

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui-custom.html