server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: Ab123456
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    default-auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.example.assignment: INFO

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui-custom.html

initial:
  price: 100

app:
  jwtSecret: 8HaCkmEifyOucan!@#7
  jwtExpirationMs: 3600000
